FROM python:3.8-slim

RUN pip install --no-cache-dir matplotlib pandas

WORKDIR /workspace
COPY ./requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt
COPY . /workspace




